"""Initial

Revision ID: fac18d31e594
Revises: 
Create Date: 2026-03-20 21:58:23.962177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac18d31e594'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.create_table('knowledgebaseitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebaseitem_entity_id'), 'knowledgebaseitem', ['entity_id'], unique=False)
    op.create_index(op.f('ix_knowledgebaseitem_graph_id'), 'knowledgebaseitem', ['graph_id'], unique=False)
    op.create_index(op.f('ix_knowledgebaseitem_tenant_id'), 'knowledgebaseitem', ['tenant_id'], unique=False)
    op.create_table('client_integration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'provider', name='unique_client_provider_integration')
    )
    op.create_index(op.f('ix_client_integration_provider'), 'client_integration', ['provider'], unique=False)
    op.create_table('connected_repository',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('installation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_repo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('ingestion_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_properties', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calls', sa.Boolean(), nullable=False),
    sa.Column('depends_on', sa.Boolean(), nullable=False),
    sa.Column('publishes_to', sa.Boolean(), nullable=False),
    sa.Column('consumes_from', sa.Boolean(), nullable=False),
    sa.Column('stores_in', sa.Boolean(), nullable=False),
    sa.Column('owned_by', sa.Boolean(), nullable=False),
    sa.Column('part_of', sa.Boolean(), nullable=False),
    sa.Column('provided_by', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_node_type_id', sa.Uuid(), nullable=True),
    sa.Column('to_node_type_id', sa.Uuid(), nullable=True),
    sa.Column('semantics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_properties', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_type_id'], ['node_type.id'], ),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_type_id'], ['node_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('node_type_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_type_id'], ['node_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'graph_id', 'key', name='unique_node_client_graph_key')
    )
    op.create_index('ix_node_client_node_type', 'node', ['client_id', 'node_type_id'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type_id', sa.Uuid(), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_type_id'], ['edge_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_client_graph_from', 'edge', ['client_id', 'graph_id', 'from_node_id'], unique=False)
    op.create_index('ix_edge_client_graph_to', 'edge', ['client_id', 'graph_id', 'to_node_id'], unique=False)
    op.create_index('ix_edge_client_type_from', 'edge', ['client_id', 'edge_type_id', 'from_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edge_client_type_from', table_name='edge')
    op.drop_index('ix_edge_client_graph_to', table_name='edge')
    op.drop_index('ix_edge_client_graph_from', table_name='edge')
    op.drop_table('edge')
    op.drop_index('ix_node_client_node_type', table_name='node')
    op.drop_table('node')
    op.drop_table('edge_type')
    op.drop_table('node_type')
    op.drop_table('graph')
    op.drop_table('connected_repository')
    op.drop_index(op.f('ix_client_integration_provider'), table_name='client_integration')
    op.drop_table('client_integration')
    op.drop_index(op.f('ix_knowledgebaseitem_tenant_id'), table_name='knowledgebaseitem')
    op.drop_index(op.f('ix_knowledgebaseitem_graph_id'), table_name='knowledgebaseitem')
    op.drop_index(op.f('ix_knowledgebaseitem_entity_id'), table_name='knowledgebaseitem')
    op.drop_table('knowledgebaseitem')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
